### ISSUE TITLE
Add version key in the manifest file

### ISSUE THREAD

**Issue by JonasStenmarck** [custom-components/sensor.brewdog#5]
**Version of the custom_component**
0b938d4

**Describe the bug**
The component can’t be loaded since homeassistant now requires a version key in the manifest for custom integrations

This should be solve by just adding the version according to:
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions

Please fix so I can have my random beer card - love it ;)

**Comment by ludeeus** [comment]
This integration needs more than just that.

But, if you want to continue to use it, change the `/config/custom_components/brewdog/manifest.json` file to this:

```json
{
    "domain": "brewdog",
    "name": "BrewDog",
    "documentation": "https://github.com/custom-components/brewdog",
    "dependencies": [],
    "version": "0.1.0",
    "codeowners": ["@ludeeus"],
    "requirements": [
      "integrationhelper==0.1.0"
    ]
}
```
